### ISSUE TITLE
Clean the mpv-youtubedl-firefox-addon.xpi

### ISSUE THREAD

**Issue by ghost** [inxp/mpv-youtubedl-firfox-addon#1]
Please check for your garbage in 'mpv-youtubedl-firefox-addon.xpi'
(Tubelight | Official Teaser | Salman Khan | Kabir Khan < 'ytdlout.txt') l0l

And, "select the available format before launching mpv." -- every time before watching?  UX? No, did not hear. But the idea of getting quality settings in the context of the video stream is interesting. I think in my fork add this feature. Maybe later...

**Comment by inxp** [comment]
Thank you for your interest.

I've cleaned the garbage. 

I didn't had any experience in JS or addon development when I made this. 

I was using both livestreamer and antoniy's 'watch with mpv' addon. Livestreamer had format selection  feature but website support is less compared to youtube-dl.

I needed this format selection feature because of the following reasons.


- My net kind of sucks sometimes forcing me to select a lower quality video.


- Different websites - Different quality - Different bandwidth required

- Sometimes youtube-dl does not support a site but it's generic extractor works, so there was no way to find out if video will open in these cases (without seeing task manger or waiting for video to open).

Existing Issues/Improvements

- Can't combine a dash video and audio using format selection UI
- Repetition of some things when playing a video after selecting format
(youtube-dl thing - repeat of 'downloading webpage', 'downloading video info', 'extracting video info' etc) which causes this to have twice delay before actual video starts playing compared to antoniy's addon.
- Switching to web-extensions if it's possible (Damn Firefox) 

It would be nice if you addressed these issues in your fork.

I'll gladly check out your fork.

Thanks

**Comment by ghost** [comment]
Ok. It's clear. 
In my fork, I made in the context menu, a choice quality for video stream formats for Youtube and Twicth (their parameters are known and stable). Without delay at UI. For other cases / sites, it is possible to add a condition to the logic, then a selection menu will appear. Or there is another option: to parse the domain and for it to choose the settings from the list / DB (which still need to be filled in):
> Сan't combine a dash video and audio using format selection UI

IMHO, it will be optimal to give the user the opportunity to add / compile their presets (for different resolutions on the same Youtube), doing this once, then using them without unnecessary delays/movements.
PS/ I'm not JS developer (l0l). And, I still work of my fork...

**Comment by inxp** [comment]
Ok. Nice work.

If I understood it correctly

Whenever user opens a site and clicks 'watch with mpv'  
Check website in DB.  If found then play using Default format selection for the website. If not found add the new website in the DB with available video stream formats. Set maximum quality by default. Let user change the default using context menu if required. 

This will get rid of double delay that my implementation has.

Things to be addressed
- What happens if first time when user visits the website, the opened video doesn't have all formats.
- What happens in case a website changes it's configuration(format code etc). Option to regenerate configuration for the website.
- What happens if the selected format is not available for a video. Should it ask for format priority instead of single default format.
- Current implementation shows both websites YouTube and twitch regardless of the website user is visiting. Context menu of websites will become very big as list of supported sites by mpv is [huge.](https://rg3.github.io/youtube-dl/supportedsites.html). Maybe change the context menu based on the current website and display options for current website only.




PS  - I've completely forget whatever JS I learned at that time.

**Comment by ghost** [comment]
> - What happens if first time when user visits the website, the opened video doesn't have all formats.

For example, in the case of YouTube, where not all formats are available for new videos, there is an option to automatically select from available formats with different prioritization. No request from the user. I think it will be faster and more convenient.

> - What happens in case a website changes it's configuration(format code etc). Option to regenerate configuration for the website.

I see two ways to solve it: Either the developer fills the database and monitors its relevance, or the user himself adds the necessary sites he visits. Or even a combination of these two ways. Of course, all this is done in a separate window. Example: this is how the settings in uBlock are implemented.

> - What happens if the selected format is not available for a video. Should it ask for format priority instead of single default format.

See above ^
In general, we want to get feedback from youtube-dl, but I do not know how to do it correctly. Also need to make various user notices. For example, if youtube-dl is not found. At your fork, there is simply infinite request of a format if the path is not specified or is specified not correctly. The same for a file mpv. This error is also in the original addon. The user should know what went wrong and where. This also applies to the inaccessibility of the file / format / stream. Need feedback.

> - Current implementation shows both websites YouTube and twitch regardless of the website user is visiting.  

In fact, the menu is always shown when the cursor is above the link (this is in the original there). Yes, there is the option to track the context, but it will be an overkill for such a task. IMHO And I'm personally lazy. But the reduction to one menu item in the context of the domain is quite within my power. IMHO too. 

> Let the user change the default value using the context menu, if necessary.

Such things are better to do in the settings of the addon and not in the context menu

PS/ Uff, the Issue can be closed. Otherwise, we'll write a wish-book here (^_^)

**Comment by inxp** [comment]
1. 👍  for user notices in case of missing paths for mpv or youtube-dl
2. 👍 for moving stuff to addon settings from context menu.
3. To get feedback from youtube-dl see `get_formats` function in my fork.
